### ISSUE TITLE
CometChatCallButtons cannot specify icon url

### ISSUE THREAD

**Issue by michaeljajou** [cometchat/cometchat-sample-app-flutter#24]
```
cometchat_chat_uikit: ^4.1.0
cometchat_calls_uikit: ^4.1.0
```

I am trying to specify a custom icon for the phone call and audio call button. 

```
CometChatCallButtons(
  user: user,
  group: group,
  voiceCallIconPackage: 'MY_PACKAGE_NAME',
  videoCallIconPackage: 'MY_PACKAGE_NAME',
  voiceCallIconURL: CoreAsset.phone.path,
  videoCallIconURL: CoreAsset.video.path,
  callButtonsStyle: const ccc.CallButtonsStyle(
    borderRadius: 8,
    videoCallIconTint: AppTheme.primaryColor,
  ),
)
```
However it throws the exception asset not found - I am specifying the package exactly as it is named on line 1 of my pubspec

**Comment by michaeljajou** [comment]
![simulator_screenshot_97C9C272-10D6-43AD-82ED-43BE9B24502A](https://github.com/cometchat/cometchat-chat-sample-app-flutter/assets/45440199/7eb29535-fc97-46e9-92e8-c8050be22eee)

```
======== Exception caught by image resource service ================================================
The following assertion was thrown resolving an image codec:
Unable to load asset: "packages/assets/icons/video.png".

Exception: Asset not found
When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.loadBuffer (package:flutter/src/services/asset_bundle.dart:365:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:754:16)
<asynchronous suspension>
#2      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:969:3)
<asynchronous suspension>
Image provider: AssetImage(bundle: null, name: "packages/assets/icons/video.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#02eb4(), name: "packages/assets/icons/video.png", scale: 1.0)
====================================================================================================

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
Trailing widget consumes entire tile width. Please use a sized widget, or consider replacing ListTile with a custom widget (see https://api.flutter.dev/flutter/material/ListTile-class.html#material.ListTile.4)
'package:flutter/src/material/list_tile.dart':
Failed assertion: line 1322 pos 7: 'tileWidth != trailingSize.width || tileWidth == 0.0'
```

**Comment by michaeljajou** [comment]
ccc.CometChatCallButtons(
          user: user,
          group: group,
          voiceCallIconPackage: 'intimid',
          videoCallIconPackage: 'intimid',
          voiceCallIconURL: CoreAsset.phone.path,
          videoCallIconURL: CoreAsset.video.path,
          callButtonsStyle: const ccc.CallButtonsStyle(
            borderRadius: 8,
            videoCallIconTint: AppTheme.primaryColor,
          ),
        )

**Comment by michaeljajou** [comment]
`name: intimid
description: "InTimid Flutter Mobile Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^10.0.0
  flutter_bloc: ^8.1.3
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  permission_handler: 10.2.0
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4
  app_settings: ^5.0.0
  webview_flutter: ^4.2.4
  url_launcher: ^6.1.14
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  email_validator: ^2.1.17
  camera: ^0.10.5+8
  collection: ^1.18.0
  share_plus: ^7.2.1
  intl: ^0.18.1
  cometchat_chat_uikit: ^4.1.0
  google_fonts: ^4.0.4
  image_cropper: ^4.0.1
  get: ^4.6.6
  cometchat_calls_uikit: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/graphics/

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/icons/app_icon.png"
  image_path_android: "assets/icons/android_app_icon.png"
  adaptive_icon_foreground: "assets/icons/android_app_icon.png"
  adaptive_icon_background: "assets/graphics/app_icon_background.png"`

**Comment by michaeljajou** [comment]
Thank you - any recent updates?

**Comment by michaeljajou** [comment]
Raising this issue again, this still doesn't seem to be working. Please provide an example of how to specify a custom icon
